[build]
  command = "yarn build"
  publish = "/opt/build/repo/public"
  functions = "/opt/build/repo/functions"
  
[[plugins]]
- inputs: {}
  origin: config
  package = "@netlify/plugin-functions-install-core"    